name: Style and integrity checks

on:
    pull_request:
        branches: ["dev"]

jobs:
    backend-checks:
        name: Backend CI
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up Node 18
              uses: actions/setup-node@v3
              env: 
                TEST_MONGO_URI: ${{ secrets.TEST_MONGO_URI }}
              with:
                node-version: 18
            - run: |
                cd backend
                npm ci
                npm run lint:check
                npm run format:check
                npm run test
              shell: bash

    frontend-checks:
        name: Frontend CI
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up Node 18
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - run: |
                cd frontend
                npm ci
                npm run lint:check
                npm run format:check
                npm run test